### ISSUE TITLE
Reference code instead of hardcode in markdown

### ISSUE THREAD

**Issue by felipe-publio** [Gustavino/map2210-trabalho1#2]
Você poderia referenciar os arquivos de código no lugar de deixar eles chumbados no markdown.

## Reference Example
https://github.com/Gustavino/map2210-trabalho1/blob/9cdffae9e27bd3ad91fd14c5c515f3661cdddd2e/development/gauss%20algorithm%20sketch.py#L1-L65

**Comment by Gustavino** [comment]
Oi, amigo...

https://github.com/Gustavino/map2210-trabalho1/blob/1fcd743ee4c4ff4e8213011ac5a865cf12afb828/main%20release/Naive%20Gauss.py#L1-L75
